version: '3.6'
services:

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    volumes:
      - ./nginx_all.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80 
    networks:
      - infinite_shiny  
  bdd:
    container_name: bdd
    image: postgres
    env_file:
      - - ../.env_1
    ports:
      - 5432:5432
    networks:
      - infinite_shiny
  rstudio:
    image: thinkr/rstudio-sspcloud
    env_file:
      - - ../.env_1
    volumes:
      - /home/ubuntu/rstudio:/home/rstudio
    ports:
      - 8787:8787
    networks:
      - infinite_shiny
networks:
  infinite_shiny:
    name: infinite_shiny