version: '3.6'
services:
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
      - 9223:9223
    networks:
      - infinite_shiny
  app:
    image: cervang/bddshow
    env_file:
      - ../.env_1
    networks:
      - infinite_shiny
  app2:
    image: cervang/bddshow
    env_file:
      - ../.env_1
    networks:
      - infinite_shiny

  api:
    image: cervang/bddshowapi
    networks:
      - infinite_shiny

  api2:
    image: cervang/bddshowapi
    networks:
      - infinite_shiny

networks:
  infinite_shiny:
    name: infinite_shiny